#Created by RuiWang

clc,clear all
lh_annot = 'D:\desktop\DK308_LUT\lh.500.aparc.annot';
rh_annot = 'D:\desktop\DK308_LUT\rh.500.aparc.annot';
region_name_file = 'D:\desktop\DK308_LUT\308_regions_names.txt';
output_LUT = 'D:\desktop\DK308_LUT\DK308_LUT.txt';

%% 1. read DK308 label
fid = fopen(region_name_file);
region_names = textscan(fid, '%s');
region_names = region_names{1};
fclose(fid);

%% 2. read DK308 annot
[~, ~, lh_colortable] = read_annotation(lh_annot);
[~, ~, rh_colortable] = read_annotation(rh_annot);

lh_names = lh_colortable.struct_names;
rh_names = rh_colortable.struct_names;

lh_colors = lh_colortable.table; % Nx5: [R G B A LabelID]
rh_colors = rh_colortable.table;
lh_names_prefixed = strcat('lh_', lh_names);
rh_names_prefixed = strcat('rh_', rh_names);

%% 3. overlap
[~, idx_lh] = intersect(lh_names_prefixed, region_names, 'stable');
[~, idx_rh] = intersect(rh_names_prefixed, region_names, 'stable');

final_names = [lh_names_prefixed(idx_lh); rh_names_prefixed(idx_rh)];
final_colors = [lh_colors(idx_lh, :); rh_colors(idx_rh, :)];

%% 4.
final_colors(:,4) = 0;

%% 5. output Freesurfer style LUT
fid = fopen(output_LUT, 'w');

fprintf(fid, '#$Id: DK308_LUT.txt, v1.0 %s Generated by RuiWang $\n\n', datestr(now,'yyyy/mm/dd'));
fprintf(fid, '#No.  Label Name:                           R   G   B   A\n\n');

for i = 1:length(final_names)
    fprintf(fid, '%-5d %-35s %3d %3d %3d %3d\n', ...
        final_colors(i,5), final_names{i}, ...
        final_colors(i,1), final_colors(i,2), ...
        final_colors(i,3), final_colors(i,4));
end
fclose(fid);

